version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: myapp-node-server
    command: npm run dev 
    ports:
      - "5000:5000"
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: myapp-react-client
    command: npm  run start
    depends_on:
      - server
    ports:
      - "3000:3000"
    

 